---
server:
    port: 9000
spring:
    datasource:
        url: jdbc:mysql://mysqldb/cards?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        password: 'root'
        username: 'root'

    jpa:
        databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect

        hibernate:

            ddl-auto: update
        show-sql: true
