---
server:
    port: 9000
spring:
    application:
        name: cards
    config:
        import: optional:configserver:http://localhost:8070/
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs