---
server:
    port: 9000
spring:
    application:
        name: cards
    profiles:
        active: prod
    config:
        import: optional:configserver:http://configserver:8070

management:
    auditevents:
        enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
